name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Packages
        run: yarn install --immutable

      - name: Linting
        run: yarn lint

      # - name: Coverage
      #   run: yarn run test:coverage

      - name: Refresh
        if: github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: yarn start
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_ONLY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_ONLY_AWS_SECRET_ACCESS_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # GitHub likes to disable workflows if a repository has been inactive for >= 60 days, this circumvents that.
      # This is incredibly silly, GitHub should add an option to disable this in the settings or a yml file.
      # https://github.com/gautamkrishnar/keepalive-workflow
      - uses: gautamkrishnar/keepalive-workflow@v1
